const strings = ["a", "b", "c", "d"]
console.log(strings)
// strings.splice()
// strings.splice(2, 0, 'x') 
// console.log(strings)
// strings.splice(2,1)
strings.splice(2,2)
console.log(strings)
strings.push('c')
strings.push('d')
console.log(strings)